function hidePreloader(){var p=document.getElementById('preloader');if(p){p.classList.add('done');setTimeout(function(){p.style.display='none';},600);}}
document.addEventListener('DOMContentLoaded',function(){setTimeout(hidePreloader,1000);initApp();});
window.addEventListener('load',function(){setTimeout(hidePreloader,400);});
setTimeout(hidePreloader,3500);

var DATA={
unitSelular:[{code:'S.951200.006.01',name:'Mencetak Ulang Kaki IC BGA',jp:20},{code:'S.951200.007.01',name:'Memperbaiki Kerusakan Telepon Seluler Mati Total',jp:30},{code:'S.951200.008.01',name:'Memperbaiki Kerusakan Lampu LED Telepon Seluler',jp:10},{code:'S.951200.009.01',name:'Memperbaiki Kerusakan Telepon Seluler Tidak Ada Tampilan dan Tidak Bisa Dimatikan dari Tombol On-Off',jp:20},{code:'S.951200.010.01',name:'Memperbaiki Kerusakan Telepon Seluler Sim Card tidak Terbaca',jp:12},{code:'S.951200.011.01',name:'Memperbaiki Kerusakan Telepon Seluler Tidak Ada Dering Buzzer',jp:10},{code:'S.951200.013.01',name:'Memperbaiki Kerusakan Telepon Seluler Tidak Ada Signal',jp:20},{code:'S.951200.015.01',name:'Memperbaiki Kerusakan Telepon Seluler pada Mic',jp:10},{code:'S.951200.018.01',name:'Memperbaiki Kerusakan Telepon Seluler pada Kamera',jp:10},{code:'S.951200.021.01',name:'Membaca Skema Telepon Seluler Aktifasi Ulang/Restart',jp:20},{code:'S.951200.024.01',name:'Memperbaiki Kerusakan Telepon Seluler Tracpad tidak Fungsi',jp:10},{code:'S.951200.025.01',name:'Memperbaiki Kerusakan Telepon Seluler Touchscreen tidak Berfungsi',jp:20},{code:'S.951200.026.01',name:'Mengoperasikan Fungsi Menu Program Flashing',jp:40}],
unitFiber:[{code:'J.61IFO00.006.2',name:'Melaksanakan Pekerjaan Secara Tim',jp:10},{code:'J.61IFO00.004.2',name:'Membuat Laporan Tertulis',jp:30},{code:'J.61IFO00.007.2',name:'Merencanakan Instalasi Fiber Optik Berdasarkan Peta As Planned Drawing',jp:30},{code:'J.61IFO00.014.2',name:'Melaksanakan Penyambungan Fiber Optik Dengan Fusion Splicer',jp:50},{code:'J.61IFO00.015.2',name:'Melaksanakan Penyambungan Fiber Optik Dengan Mechanical Splice',jp:30},{code:'J.61IFO00.016.2',name:'Mengoperasikan OTDR (Optical Time Domain Reflectometer)',jp:40},{code:'J.61IFO00.017.2',name:'Melaksanakan Evaluasi Instalasi Fiber Optik Menggunakan OTDR',jp:42}],
alatSelular:['Multitester','Solder Uap','Solder Station','Pinset','Obeng Handphone','Lampu Service','Penjepit PCB','Dudukan Solder','Kaca Pembesar','Sikat Pembersih','Power Supply','UFI Box','Power Supply Predator','Komputer','Botol Alkohol'],
bahanSelular:['Timah Gulung','Timah Cair','Mata Solder Station','Pasta Solder','Solder Wick','Flux','LCD + Touch Screen','IC EMMC','IC Power','IC RF','IC Charging','Mic','LED','Buzzer','Konektor Charging','Konektor Baterai','Switch On-Off','Simcard Connector','Kabel Data','Mesin HP Android','Kabel Jumper','Plat Cetak IC Universal','Plat Cetak IC EMMC','Ragum HP','PCB Lubang','Pinset Lancip','Pinset Bengkok','Pisau IC','Obeng Khusus HP','Isolasi Kertas','Isolasi Aluminium','Resistor SMD','Kapasitor SMD','Tiner','Botol Tiner','Sikat Gigi','Kertas A4','Kotak P3K','Tisu','Kain Majun','Masker Kain'],
alatFiber:['Kertas','Bolpoint','Komputer','Printer','Alat Peraga Komponen Aktif/Pasif','Tang Potong Sedang','Tang Potong Kecil','Tang Buaya','Tang Kombinasi','Cutter','Gunting Kabel','Fusion Splicer','Hot Gun','Pemotong Piva','Gergaji Besi','ToolBox','Mechanical Splicer','Kunci Pas','Tangga Telescopic 4m','Kuas Cleaner','Sleeve Protector','OTDR'],
bahanFiber:['Kabel Ties 10cm','Kabel Ties 15cm','Label','Tissue Splicing','Sealer Karet','Heatshrink (berbagai ukuran)','Flexible Spiral Kabel','Spidol Permanen','Solasi 3M','Double Tip Clamp','Minyak Tanah','Kabel Optik','Karpet Plastik 2x2m']
};
var curStep=1,selItems=[],custItems=[];

function initApp(){try{initNav();initTrain();initScroll();setDT();genU('unitSelularList',DATA.unitSelular);genU('unitFiberList',DATA.unitFiber);animS();}catch(e){console.error(e);}}

// NAV
function initNav(){var ls=document.querySelectorAll('.navlink');for(var i=0;i<ls.length;i++)ls[i].addEventListener('click',function(e){e.preventDefault();navigateTo(this.getAttribute('data-section'));});}
function navigateTo(id){var ls=document.querySelectorAll('.navlink');for(var i=0;i<ls.length;i++)ls[i].classList.remove('active');var a=document.querySelector('.navlink[data-section="'+id+'"]');if(a)a.classList.add('active');var ms=document.querySelectorAll('.mm-link');for(var i=0;i<ms.length;i++)ms[i].classList.remove('active');var m=document.querySelector('.mm-link[data-section="'+id+'"]');if(m)m.classList.add('active');var ps=document.querySelectorAll('.page');for(var i=0;i<ps.length;i++)ps[i].classList.remove('active');var t=document.getElementById(id);if(t){t.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}}
function toggleMenu(){var h=document.getElementById('hamburger'),m=document.getElementById('mobileMenu');h.classList.toggle('open');m.classList.toggle('open');}
function navTo(id){navigateTo(id);var h=document.getElementById('hamburger'),m=document.getElementById('mobileMenu');h.classList.remove('open');m.classList.remove('open');}

function initScroll(){window.addEventListener('scroll',function(){var n=document.getElementById('navbar'),b=document.getElementById('btt');if(n){if(window.scrollY>30)n.classList.add('scrolled');else n.classList.remove('scrolled');}if(b){if(window.scrollY>200)b.classList.add('show');else b.classList.remove('show');}});}
function setDT(){var n=new Date(),d=document.getElementById('tanggalPinjam'),t=document.getElementById('waktuPinjam');if(d)d.value=n.toISOString().split('T')[0];if(t)t.value=n.getHours().toString().padStart(2,'0')+':'+n.getMinutes().toString().padStart(2,'0');}

// STEPS
function goToStep(tgt){if(tgt>curStep&&!valStep(curStep))return;var ss=document.querySelectorAll('.steps .stp'),ls=document.querySelectorAll('.steps .stp-line');for(var i=0;i<ss.length;i++){ss[i].classList.remove('active','done');if(i<tgt-1)ss[i].classList.add('done');if(i===tgt-1)ss[i].classList.add('active');}for(var i=0;i<ls.length;i++){if(i<tgt-1)ls[i].classList.add('active');else ls[i].classList.remove('active');}var fs=document.querySelectorAll('.fstep');for(var i=0;i<fs.length;i++)fs[i].classList.remove('active');var ts=document.getElementById('step'+tgt);if(ts)ts.classList.add('active');curStep=tgt;if(tgt===3)loadItems();if(tgt===4)genPreview();window.scrollTo({top:120,behavior:'smooth'});}
function valStep(s){if(s===1){if(!document.getElementById('namaPeserta').value.trim()){toast('Nama harus diisi!','error');return false;}if(!document.getElementById('noPeserta').value.trim()){toast('No. Peserta harus diisi!','error');return false;}if(!document.getElementById('tanggalPinjam').value){toast('Tanggal harus diisi!','error');return false;}if(!document.querySelector('input[name="instruktur"]:checked')){toast('Pilih instruktur!','error');return false;}return true;}if(s===2){var p=document.querySelector('input[name="jenisPelatihan"]:checked');if(!p){toast('Pilih pelatihan!','error');return false;}var lid=p.value.indexOf('Telepon')!==-1?'unitSelularList':'unitFiberList';if(!document.querySelectorAll('#'+lid+' input:checked').length){toast('Pilih minimal 1 unit!','error');return false;}return true;}if(s===3){collectItems();if(!selItems.length){toast('Pilih minimal 1 item!','error');return false;}return true;}return true;}

// TRAINING
function initTrain(){var rs=document.querySelectorAll('input[name="jenisPelatihan"]');for(var i=0;i<rs.length;i++)rs[i].addEventListener('change',function(){var us=document.getElementById('unitSelular'),uf=document.getElementById('unitFiber');if(this.value.indexOf('Telepon')!==-1){us.className='unit-box show';uf.className='unit-box hidden';}else{uf.className='unit-box show';us.className='unit-box hidden';}selItems=[];custItems=[];var cl=document.getElementById('customList');if(cl)cl.innerHTML='';});}

// UNITS
function genU(cid,units){var c=document.getElementById(cid);if(!c)return;c.innerHTML='';for(var i=0;i<units.length;i++){var u=units[i],l=document.createElement('label');l.className='unit-item';l.innerHTML='<input type="checkbox" name="u_'+cid+'" value="'+u.code+'||'+u.name+'||'+u.jp+'"><div class="u-info"><div class="u-chk"><i class="fas fa-check"></i></div><div class="u-detail"><div class="u-code">'+u.code+'</div><div class="u-name">1.'+(i+1)+'. '+u.name+'</div></div><div class="u-jp">'+u.jp+' JP</div></div>';c.appendChild(l);}}
function selAll(t){var id=t==='selular'?'selAllS':'selAllF',lid=t==='selular'?'unitSelularList':'unitFiberList',v=document.getElementById(id).checked,bs=document.querySelectorAll('#'+lid+' input[type="checkbox"]');for(var i=0;i<bs.length;i++)bs[i].checked=v;}

// TABS
function openTab(t){var bs=document.querySelectorAll('.tab');for(var i=0;i<bs.length;i++)bs[i].classList.remove('active');var a=document.querySelector('.tab[data-tab="'+t+'"]');if(a)a.classList.add('active');var ps=document.querySelectorAll('.tabpanel');for(var i=0;i<ps.length;i++)ps[i].classList.remove('active');var tp=document.getElementById('tab-'+t);if(tp)tp.classList.add('active');}

// ITEMS
function loadItems(){var p=document.querySelector('input[name="jenisPelatihan"]:checked');if(!p)return;var isS=p.value.indexOf('Telepon')!==-1;buildGrid('alatGrid',isS?DATA.alatSelular:DATA.alatFiber,'alat');buildGrid('bahanGrid',isS?DATA.bahanSelular:DATA.bahanFiber,'bahan');for(var i=0;i<custItems.length;i++){var ci=custItems[i];addToGrid(ci,ci.type==='Peralatan'?'alatGrid':'bahanGrid',ci.type==='Peralatan'?'alat':'bahan');}updSummary();}
function buildGrid(gid,items,type){var g=document.getElementById(gid);if(!g)return;g.innerHTML='';for(var i=0;i<items.length;i++){var nm=items[i],pr=null;for(var j=0;j<selItems.length;j++){if(selItems[j].name===nm){pr=selItems[j];break;}}var c=document.createElement('label');c.className='icard';c.setAttribute('data-name',nm.toLowerCase());c.innerHTML='<input type="checkbox" name="it_'+type+'" value="'+type+'||'+nm+'" '+(pr?'checked':'')+' onchange="updSummary()"><div class="i-inner"><div class="i-ic '+type+'"><i class="fas fa-'+(type==='alat'?'wrench':'cube')+'"></i></div><span class="i-name">'+nm+'</span><div class="i-qty"><input type="number" min="1" value="'+(pr?pr.qty:1)+'" onclick="event.stopPropagation()" onchange="updSummary()" class="qinp"></div></div>';g.appendChild(c);}}
function filterItems(t){var q=document.getElementById(t==='alat'?'searchAlat':'searchBahan').value.toLowerCase(),cs=document.querySelectorAll('#'+(t==='alat'?'alatGrid':'bahanGrid')+' .icard');for(var i=0;i<cs.length;i++)cs[i].style.display=cs[i].getAttribute('data-name').indexOf(q)!==-1?'':'none';}
function selAllItems(t){var v=document.getElementById(t==='alat'?'selAllAlat':'selAllBahan').checked,bs=document.querySelectorAll('#'+(t==='alat'?'alatGrid':'bahanGrid')+' input[type="checkbox"]');for(var i=0;i<bs.length;i++){var c=bs[i].closest('.icard');if(c&&c.style.display!=='none')bs[i].checked=v;}updSummary();}

// CUSTOM
function addCustom(){var nm=document.getElementById('customName').value.trim(),tp=document.getElementById('customType').value,qt=parseInt(document.getElementById('customQty').value)||1,nt=document.getElementById('customNote').value.trim();if(!nm){toast('Nama harus diisi!','error');return;}for(var i=0;i<custItems.length;i++){if(custItems[i].name.toLowerCase()===nm.toLowerCase()){toast('Sudah ada!','warning');return;}}var ci={name:nm,type:tp,qty:qt,note:nt};custItems.push(ci);addToGrid(ci,tp==='Peralatan'?'alatGrid':'bahanGrid',tp==='Peralatan'?'alat':'bahan');renderCL();document.getElementById('customName').value='';document.getElementById('customQty').value='1';document.getElementById('customNote').value='';toast('"'+nm+'" ditambahkan!','success');updSummary();}
function addToGrid(ci,gid,it){var g=document.getElementById(gid);if(!g)return;var c=document.createElement('label');c.className='icard';c.setAttribute('data-name',ci.name.toLowerCase());c.innerHTML='<input type="checkbox" name="it_'+it+'" value="'+it+'||'+ci.name+'" checked onchange="updSummary()"><div class="i-inner" style="border-color:rgba(245,158,11,.2);"><div class="i-ic cust"><i class="fas fa-star"></i></div><span class="i-name">'+ci.name+(ci.note?' ('+ci.note+')':'')+' <em style="font-size:9px;color:var(--amb);">[C]</em></span><div class="i-qty"><input type="number" min="1" value="'+ci.qty+'" onclick="event.stopPropagation()" onchange="updSummary()" class="qinp"></div></div>';g.appendChild(c);}
function renderCL(){var l=document.getElementById('customList');if(!l)return;l.innerHTML='';for(var i=0;i<custItems.length;i++){var ci=custItems[i],d=document.createElement('div');d.className='cust-tag';d.innerHTML='<span><i class="fas fa-star" style="color:var(--amb);margin-right:5px;"></i><strong>'+ci.name+'</strong> — '+ci.type+' ('+ci.qty+')</span><span class="rm" onclick="rmCust('+i+')"><i class="fas fa-times-circle"></i></span>';l.appendChild(d);}}
function rmCust(i){var r=custItems.splice(i,1)[0];renderCL();var cs=document.querySelectorAll('.icard');for(var j=0;j<cs.length;j++){if(cs[j].getAttribute('data-name')===r.name.toLowerCase())cs[j].remove();}updSummary();toast('"'+r.name+'" dihapus','info');}

// SELECTED
function collectItems(){selItems=[];var ch=document.querySelectorAll('input[name^="it_"]:checked');for(var i=0;i<ch.length;i++){var p=ch[i].value.split('||'),c=ch[i].closest('.icard'),q=c?c.querySelector('.qinp'):null;selItems.push({type:p[0],name:p[1],qty:q?(parseInt(q.value)||1):1});}}
function updSummary(){collectItems();var l=document.getElementById('selList'),c=document.getElementById('selCount');if(!l||!c)return;c.textContent=selItems.length;if(!selItems.length){l.innerHTML='<p class="ss-empty">Belum ada item dipilih</p>';return;}l.innerHTML='';for(var i=0;i<selItems.length;i++){var t=document.createElement('span');t.className='ss-tag';t.innerHTML='<i class="fas fa-'+(selItems[i].type==='alat'?'wrench':'cube')+'"></i> '+selItems[i].name+' ('+selItems[i].qty+')';l.appendChild(t);}}

// KOP
function KOP(){return '<div style="text-align:center;border-bottom:3px double #000;padding-bottom:10px;margin-bottom:14px;"><p style="font-size:12pt;font-weight:bold;margin:0;line-height:1.25;">KEMENTERIAN KETENAGAKERJAAN REPUBLIK INDONESIA</p><p style="font-size:10pt;font-weight:bold;margin:0;line-height:1.25;">DIREKTORAT JENDERAL</p><p style="font-size:10pt;font-weight:bold;margin:0;line-height:1.25;">PEMBINAAN PELATIHAN VOKASI DAN PRODUKTIVITAS</p><p style="font-size:11pt;font-weight:bold;margin:2px 0 0;line-height:1.25;">BALAI PELATIHAN VOKASI DAN PRODUKTIVITAS SORONG</p><p style="font-size:8pt;margin:2px 0 0;">Jl. Basuki Rahmat KM. 9,5 Telp/Fax (0951) 324776 Sorong Papua Barat Daya</p><p style="font-size:8pt;margin:1px 0 0;">Website: https://bpvpsorong.kemnaker.go.id</p></div>';}
function SGN(nK,nR,lK,lR){return '<div style="text-align:center;margin-top:35px;"><p style="font-size:11pt;font-weight:bold;margin:0 0 5px;">Mengetahui,</p></div><table style="width:100%;border-collapse:collapse;"><tr><td style="width:50%;text-align:center;vertical-align:top;border:none;padding:4px 12px 0;"><p style="font-size:10pt;margin:0 0 2px;">'+lK+'</p><div style="height:75px;width:170px;margin:0 auto;border-bottom:1px solid #000;"></div><p style="font-weight:bold;font-size:10pt;margin:5px 0 0;text-decoration:underline;">'+nK+'</p><p style="font-size:7pt;color:#888;font-style:italic;margin:1px 0 0;">TTD Basah</p></td><td style="width:50%;text-align:center;vertical-align:top;border:none;padding:4px 12px 0;"><p style="font-size:10pt;margin:0 0 2px;">'+lR+'</p><div style="height:75px;width:170px;margin:0 auto;border-bottom:1px solid #000;"></div><p style="font-weight:bold;font-size:10pt;margin:5px 0 0;text-decoration:underline;">'+nR+'</p><p style="font-size:7pt;color:#888;font-style:italic;margin:1px 0 0;">TTD Basah</p></td></tr></table>';}
function INF(a,b,c,d,e,f){return '<table style="width:100%;border-collapse:collapse;margin-bottom:10px;"><tr><td style="padding:2px 5px;width:150px;font-weight:bold;font-size:10pt;border:none;">Nama Peserta</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+a+'</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">No. Peserta / NIK</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+b+'</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">Tanggal</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+fmtD(c)+'</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">Waktu</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+(d||'-')+'</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">Jenis Pelatihan</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+e+'</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">Instruktur</td><td style="padding:2px 5px;font-size:10pt;border:none;">: '+f+'</td></tr></table>';}
function TH(t,w){return '<th style="border:1px solid #000;padding:3px 4px;background:#e8e8e8;text-align:center;font-size:8.5pt;font-weight:bold;'+(w?'width:'+w+';':'')+'">'+t+'</th>';}
function TD(t,a,b){return '<td style="border:1px solid #000;padding:2px 4px;font-size:8.5pt;'+(a?'text-align:'+a+';':'')+(b?'font-weight:bold;':'')+'">'+t+'</td>';}

function genPreview(){collectItems();var nm=document.getElementById('namaPeserta').value,np=document.getElementById('noPeserta').value,tg=document.getElementById('tanggalPinjam').value,wk=document.getElementById('waktuPinjam').value,ins=document.querySelector('input[name="instruktur"]:checked').value,pl=document.querySelector('input[name="jenisPelatihan"]:checked').value,cat=document.getElementById('catatan').value;
var isS=pl.indexOf('Telepon')!==-1,lid=isS?'unitSelularList':'unitFiberList',units=[],ub=document.querySelectorAll('#'+lid+' input:checked');
for(var i=0;i<ub.length;i++){var p=ub[i].value.split('||');units.push({c:p[0],n:p[1],j:p[2]});}
var tJ=0;for(var i=0;i<units.length;i++)tJ+=parseInt(units[i].j)||0;
var aI=[],bI=[];for(var i=0;i<selItems.length;i++){if(selItems[i].type==='alat')aI.push(selItems[i]);else bI.push(selItems[i]);}

// P1
var p1=KOP()+'<p style="text-align:center;margin:12px 0;font-size:11pt;font-weight:bold;text-decoration:underline;">FORMULIR PEMINJAMAN PERALATAN DAN PENGGUNAAN BAHAN PELATIHAN</p>'+INF(nm,np,tg,wk,pl,ins);
p1+='<p style="font-weight:bold;margin:8px 0 3px;font-size:9.5pt;">I. UNIT KOMPETENSI</p><table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><thead><tr>'+TH('No','22px')+TH('Kode','100px')+TH('Unit Kompetensi','')+TH('JP','28px')+'</tr></thead><tbody>';
for(var i=0;i<units.length;i++)p1+='<tr>'+TD(i+1,'center')+TD(units[i].c)+TD(units[i].n)+TD(units[i].j,'center')+'</tr>';
p1+='<tr><td colspan="3" style="border:1px solid #000;padding:2px 4px;text-align:right;font-weight:bold;font-size:8.5pt;">Total</td>'+TD(tJ,'center',true)+'</tr></tbody></table>';
var sc=2;
if(aI.length){p1+='<p style="font-weight:bold;margin:6px 0 3px;font-size:9.5pt;">II. PERALATAN</p><table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><thead><tr>'+TH('No','22px')+TH('Nama','')+TH('Jml','26px')+TH('Kondisi Pinjam','68px')+TH('Kondisi Kembali','68px')+'</tr></thead><tbody>';for(var i=0;i<aI.length;i++)p1+='<tr>'+TD(i+1,'center')+TD(aI[i].name)+TD(aI[i].qty,'center')+TD('Baik','center')+TD('')+'</tr>';p1+='</tbody></table>';sc=3;}
if(bI.length){p1+='<p style="font-weight:bold;margin:6px 0 3px;font-size:9.5pt;">'+(sc===3?'III':'II')+'. BAHAN</p><table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><thead><tr>'+TH('No','22px')+TH('Nama','')+TH('Jml','26px')+TH('Keterangan','110px')+'</tr></thead><tbody>';for(var i=0;i<bI.length;i++)p1+='<tr>'+TD(i+1,'center')+TD(bI[i].name)+TD(bI[i].qty,'center')+TD('')+'</tr>';p1+='</tbody></table>';}
if(cat)p1+='<p style="font-size:8.5pt;margin:4px 0;"><b>Catatan:</b> '+cat+'</p>';
p1+=SGN(nm,ins,'Peminjam / Peserta','Instruktur Pelatihan');
p1+='<div style="margin-top:18px;text-align:center;font-size:6.5pt;color:#bbb;border-top:1px solid #eee;padding-top:4px;">Halaman 1 — Formulir Peminjaman</div>';

// P2
var p2=KOP()+'<p style="text-align:center;margin:12px 0;font-size:11pt;font-weight:bold;text-decoration:underline;">FORMULIR PENGEMBALIAN PERALATAN DAN BAHAN PELATIHAN</p>'+INF(nm,np,tg,wk,pl,ins);
p2+='<table style="width:100%;border-collapse:collapse;margin-bottom:10px;"><tr><td style="padding:2px 5px;width:150px;font-weight:bold;font-size:10pt;border:none;">Tgl Pengembalian</td><td style="padding:2px 5px;font-size:10pt;border:none;">: .................................</td></tr><tr><td style="padding:2px 5px;font-weight:bold;font-size:10pt;border:none;">Waktu Pengembalian</td><td style="padding:2px 5px;font-size:10pt;border:none;">: .................................</td></tr></table>';
if(aI.length){p2+='<p style="font-weight:bold;margin:6px 0 3px;font-size:9.5pt;">I. PENGEMBALIAN PERALATAN</p><table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><thead><tr>'+TH('No','22px')+TH('Nama','')+TH('Pinjam','38px')+TH('Kembali','38px')+TH('Kondisi','62px')+TH('Ket.','70px')+'</tr></thead><tbody>';for(var i=0;i<aI.length;i++)p2+='<tr>'+TD(i+1,'center')+TD(aI[i].name)+TD(aI[i].qty,'center')+TD('','center')+TD('')+TD('')+'</tr>';p2+='</tbody></table>';}
if(bI.length){var rr=aI.length?'II':'I';p2+='<p style="font-weight:bold;margin:6px 0 3px;font-size:9.5pt;">'+rr+'. SISA BAHAN</p><table style="width:100%;border-collapse:collapse;margin-bottom:8px;"><thead><tr>'+TH('No','22px')+TH('Nama','')+TH('Pakai','36px')+TH('Sisa','36px')+TH('Kembali','38px')+TH('Ket.','70px')+'</tr></thead><tbody>';for(var i=0;i<bI.length;i++)p2+='<tr>'+TD(i+1,'center')+TD(bI[i].name)+TD(bI[i].qty,'center')+TD('','center')+TD('','center')+TD('')+'</tr>';p2+='</tbody></table>';}
p2+='<p style="font-weight:bold;margin:6px 0 3px;font-size:9.5pt;">Catatan Pengembalian:</p><table style="width:100%;border-collapse:collapse;margin-bottom:4px;"><tr>'+TD('1','center')+'<td style="border:1px solid #000;padding:2px 4px;font-size:8.5pt;">Semua peralatan kembali baik</td>'+TD('Ya / Tidak *)','center')+'</tr><tr>'+TD('2','center')+'<td style="border:1px solid #000;padding:2px 4px;font-size:8.5pt;">Ada peralatan rusak/hilang</td>'+TD('Ya / Tidak *)','center')+'</tr><tr>'+TD('3','center')+'<td style="border:1px solid #000;padding:2px 4px;font-size:8.5pt;">Sisa bahan dikembalikan</td>'+TD('Ya / Tidak *)','center')+'</tr></table><p style="font-size:6.5pt;color:#666;font-style:italic;">*) Coret yang tidak perlu</p><p style="font-size:8.5pt;margin:4px 0;">Keterangan: .........................................................................................................................................................................................................</p>';
p2+=SGN(nm,ins,'Yang Mengembalikan','Yang Menerima / Instruktur');
p2+='<div style="margin-top:18px;text-align:center;font-size:6.5pt;color:#bbb;border-top:1px solid #eee;padding-top:4px;">Halaman 2 — Formulir Pengembalian</div>';

var pv=document.getElementById('previewDoc');if(pv)pv.innerHTML='<div>'+p1+'</div><div style="page-break-before:always;"></div><div>'+p2+'</div>';}

// CETAK
function cetakDokumen(){var pv=document.getElementById('previewDoc');if(!pv)return;var c=pv.innerHTML,pw=window.open('','_blank');if(!pw){toast('Pop-up diblokir!','error');return;}pw.document.open();pw.document.write('<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Formulir BPVP Sorong</title><style>@page{margin:12mm 14mm;size:A4;}*{margin:0;padding:0;box-sizing:border-box;}body{font-family:"Times New Roman",serif;font-size:12pt;line-height:1.4;color:#000;background:#fff;padding:5px;}p,td,th,span,strong{color:#000!important;}table{border-collapse:collapse;page-break-inside:auto;}tr{page-break-inside:avoid;}</style></head><body>'+c+'<script>window.onload=function(){setTimeout(function(){window.print();},500);};<\/script></body></html>');pw.document.close();}

// RESET
function resetForm(){if(!confirm('Reset form?'))return;var f=document.getElementById('mainForm');if(f)f.reset();curStep=1;selItems=[];custItems=[];var fs=document.querySelectorAll('.fstep');for(var i=0;i<fs.length;i++)fs[i].classList.remove('active');document.getElementById('step1').classList.add('active');var ss=document.querySelectorAll('.steps .stp');for(var i=0;i<ss.length;i++){ss[i].classList.remove('active','done');if(i===0)ss[i].classList.add('active');}var ls=document.querySelectorAll('.stp-line');for(var i=0;i<ls.length;i++)ls[i].classList.remove('active');document.getElementById('unitSelular').className='unit-box hidden';document.getElementById('unitFiber').className='unit-box hidden';var cl=document.getElementById('customList');if(cl)cl.innerHTML='';var ag=document.getElementById('alatGrid');if(ag)ag.innerHTML='';var bg=document.getElementById('bahanGrid');if(bg)bg.innerHTML='';setDT();window.scrollTo({top:120,behavior:'smooth'});toast('Form direset!','success');}

// TOAST
function toast(m,t){var c=document.getElementById('toasts');if(!c)return;var d=document.createElement('div');d.className='toast '+(t||'info');var ic={success:'fa-check-circle',error:'fa-exclamation-circle',warning:'fa-exclamation-triangle',info:'fa-info-circle'};d.innerHTML='<i class="fas '+(ic[t]||ic.info)+'"></i> '+m;c.appendChild(d);setTimeout(function(){d.classList.add('out');setTimeout(function(){if(d.parentNode)d.remove();},300);},3000);}

// UTIL
function fmtD(s){if(!s)return'-';var m=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];var d=new Date(s);return d.getDate()+' '+m[d.getMonth()]+' '+d.getFullYear();}
function animS(){setTimeout(function(){animN('totalAlat',DATA.alatSelular.length+DATA.alatFiber.length);animN('totalBahan',DATA.bahanSelular.length+DATA.bahanFiber.length);},1500);}
function animN(id,tg){var e=document.getElementById(id);if(!e)return;var c=0,s=Math.ceil(tg/20);var t=setInterval(function(){c+=s;if(c>=tg){c=tg;clearInterval(t);}e.textContent=c;},50);}